### PR TITLE
Add terms and privacy policy for Sandcats

### PR DESCRIPTION
**Pull request by kentonv**
@paulproteus, please review. Note that if you want to see the diff against Oasis' policy, skip the first commit.

### CODE REVIEW

**Comment by paulproteus** [comment]
Feedback, not necessarily show-stoppers:

Privacy policy:
- Arguably in "Data gathered from you, and how we use it" we also gather a "chosen hostname".

Terms of Service:
- The "You may use the Sandcats service in conjunction with a server..." paragraph doesn't quite state clearly to me exactly how out-of-date people's Sandstorm installs may be, before we break their access to the service intentionally.
- "we may cease responding to DNS queries for your Sandcats subdomain and may revoke any TLS certificates associated with it" => "we may cease responding to DNS queries for your Sandcats subdomain and may revoke any TLS certificates associated with it and cease responding to requests for more certificates" maybe.

One interesting thing is that I did modify Sandcats so that it limits people to 4 active certificates at a time. I see this as both a workaround for a bug last week as well as an anti-abuse tactic. Do you think anti-abuse tactics like that deserve a mention here?

I think that's all I have. I'll work on creating URLs for this under `sandcats.io` and merging this now, and if you want to make changes based on the above, cool, I'll look for them.

**Comment by paulproteus** [comment]
Oh, I see, I can't merge this in `tos-pp`, but I can look for the scripts that convert this to HTML etc. anyway.

**Comment by kentonv** [comment]
> The "You may use the Sandcats service in conjunction with a server..." paragraph doesn't quite state clearly to me exactly how out-of-date people's Sandstorm installs may be

It says "a month".

> "we may cease responding to DNS queries...

Changing to more general "we may stop providing service for your Sandcats subdomain".

New commit pushed, please review.

**Comment by paulproteus** [comment]
+1

**Pull request merged**
